import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { techScoutApi } from "../api";
import { syntheticNotice } from "../api/techscoutFixtures";
import { messageForTechScoutIssue } from "../api/techscoutIssues";
import { useTechScoutRunPolling } from "../polling/useTechScoutRunPolling";
import { useResource } from "./useResource";
import { useI18n } from "../i18n";

export function RunPage() {
  const { locale, t } = useI18n(); const stages = [{ id: "plan", label: t("plan"), note: t("planNote") }, { id: "research", label: t("research"), note: t("researchNote") }, { id: "verify", label: t("verify"), note: t("verifyNote") }, { id: "decide", label: t("decide"), note: t("decideNote") }] as const;
  const { id = "" } = useParams(); const { run, error, connectionLost, loading } = useTechScoutRunPolling(id, techScoutApi); const [traceOpen, setTraceOpen] = useState(false); const trace = useResource(() => techScoutApi.getTrace(id, undefined, 50).then((response) => response.data), [id, traceOpen]);
  if (loading) return <div className="page-state">{t("loadingRun")}</div>; if (error || !run) return <div className="page-state" role="alert">{error?.message ?? t("runMissing")}</div>;
  return <article className="tech-run">{run.synthetic && <div className="synthetic-ribbon" role="note">{locale === "en" ? syntheticNotice : t("syntheticBoundary")}</div>}{connectionLost && <div className="connection-banner" role="alert">{t("connection")}</div>}
    <header className="run-title"><div><p className="eyebrow" role="status" aria-live="polite">{run.mode} mode · {run.status.replaceAll("_", " ")}</p><h1>{run.question}</h1></div><div className="elapsed"><strong>{run.progress.elapsed_seconds.toFixed(1)}s</strong><span>{run.synthetic ? t("fixtureElapsed") : t("elapsed")}</span></div></header>
    {run.status === "failed" && <section className="terminal-notice failed" role="alert"><strong>{t("failed")}</strong><p>{t("failedHelp")}</p>{run.issues.map((issue) => <div key={`${issue.stage}-${issue.code}`}><code>{issue.stage} / {issue.code}</code><span>{messageForTechScoutIssue(issue.code, locale)}</span>{issue.retryable_by_new_run && <small>{t("retry")}</small>}</div>)}</section>}
    {run.status === "completed_with_limitations" && <section className="terminal-notice limited" role="status"><strong>{t("limited")}</strong><p>{t("limitedHelp")}</p>{run.issues.map((issue) => <div key={`${issue.stage}-${issue.code}`}><code>{issue.code}</code><span>{messageForTechScoutIssue(issue.code, locale)}</span></div>)}</section>}
    <ol className="stage-track" aria-label={t("progress")}>{stages.map((stage, index) => { const complete = run.progress.completed_stages.includes(stage.id); const current = run.progress.stage === stage.id; const state = complete ? t("completed") : current ? t("current") : t("pending"); return <li key={stage.id} className={complete ? "complete" : current ? "current" : ""} aria-current={current ? "step" : undefined}><span>{String(index + 1).padStart(2, "0")}</span><strong>{stage.label}</strong><small>{stage.note}</small><span className="sr-only">{state}</span></li>; })}</ol>
    <section className="now-panel"><div><span>{t("currentSkill")}</span><strong>{run.progress.current_skill ?? "—"}</strong></div><div><span>{t("currentTool")}</span><strong>{run.progress.current_tool ?? "—"}</strong></div><div><span>{t("approval")}</span><strong>{run.approval.status.replaceAll("_", " ")}</strong></div><div><span>{t("recovery")}</span><strong>{run.recovery.outcome.replaceAll("_", " ")} · {run.recovery.attempts_used}/1</strong></div></section>
    <section className="candidate-board"><header><p className="eyebrow">{t("matrix")}</p><h2>{run.candidates.length ? `${run.candidates.length} ${t("components")}` : t("awaiting")}</h2></header><div>{run.candidates.map((candidate) => <Link key={candidate.candidate_id} to={`/runs/${id}/candidates/${encodeURIComponent(candidate.candidate_id)}`}><span className="candidate-index">{candidate.candidate_id}</span><strong>{candidate.name}</strong><small>{candidate.support_level.replaceAll("_", " ")}</small><b>{candidate.verdict.replaceAll("_", " ")}</b></Link>)}</div></section>
    {(run.status === "completed" || run.status === "completed_with_limitations") && <div className="run-links"><Link to={`/runs/${id}/report`}>{t("openReport")}</Link></div>}
    <section className="trace-drawer"><button aria-expanded={traceOpen} onClick={() => setTraceOpen(!traceOpen)}>{t("trace")} <span>{traceOpen ? t("collapse") : t("expand")}</span></button>{traceOpen && <ol>{trace.data?.items.map((event) => <li key={event.cursor}><time>{event.stage ?? event.event_type}</time><div><strong>{event.label}</strong><small>{[event.skill, event.tool, event.duration_ms == null ? null : `${event.duration_ms} ms`].filter(Boolean).join(" · ")}</small></div></li>)}</ol>}</section>
  </article>;
}
