import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Locale = "en" | "zh-CN";
const STORAGE_KEY = "momo-techscout-locale:v1";

const messages = {
  en: {
    skip: "Skip to content", fixture: "Synthetic fixture mode · simulated lifecycle · no provider, network, or Docker calls", syntheticBoundary: "Synthetic frozen demo — real Harness and local MCP routing, but no live provider evidence or real Docker claim.", home: "MOMO TechScout home", desk: "Evidence & verification desk", footerWave: "MOMO TechScout / local Wave 2 integration", footerRule: "Evidence before recommendation.", language: "Language", english: "English", chinese: "中文",
    heroEye: "Wave 2 · Harness-backed component research", heroTitleA: "Choose with", heroTitleB: "receipts.", heroDek: "Compare Python AI components against hard constraints, frozen evidence over local MCP, and deterministic allowlisted checks.", boundary: "Fast Demo boundary", vectorStores: "Local RAG vector stores", boundaryBody: "Fast Demo is synthetic and offline. Verified mode uses live providers and reviewed Docker only when those authorities are available.",
    newTask: "New task", frame: "Frame the decision", question: "Decision question", questionPlaceholder: "Which local vector store fits this service?", project: "Project context", python: "Python", os: "Operating system", deployment: "Deployment", constraints: "Hard constraints", constraintsHint: "one per line, maximum five", candidates: "Candidate shortlist", candidatesHint: "optional, comma-separated, maximum three", mode: "Mode", fast: "Fast Demo", verified: "Verified (Live + reviewed Docker)", submitting: "Submitting…", start: "Start TechScout task", recent: "Recent runs", ledger: "Decision ledger", fixtureTitle: "Synthetic offline fixture", fixtureBody: "No live evidence, provider, Docker, or evaluation claims.",
    loadingRun: "Loading run projection…", runMissing: "Run not found.", connection: "Connection lost — retaining the last known state and retrying with backoff.", fixtureElapsed: "fixture elapsed", elapsed: "elapsed", failed: "Run failed safely — no report was published.", failedHelp: "Review the stable failure code below, then start a new task if the condition is retryable.", retry: "Retry by starting a new run.", limited: "Completed with limitations.", limitedHelp: "The report is available, but the following boundaries remain material.", progress: "TechScout progress", plan: "Plan", planNote: "freeze the question", research: "Research", researchNote: "collect official evidence", verify: "Verify", verifyNote: "run trusted recipes", decide: "Decide", decideNote: "apply deterministic gates", completed: "completed", current: "current", pending: "pending", currentSkill: "Current skill", currentTool: "Current tool", approval: "Approval", recovery: "Recovery", matrix: "Candidate matrix", awaiting: "Awaiting candidate projection", components: "components", openReport: "Open decision report →", trace: "Trace feed", collapse: "Collapse", expand: "Expand",
    loadingReport: "Loading decision report…", decisionReport: "Decision report", recommend: "Recommend", noWinner: "No safe winner", timeline: "← Run timeline", hardConstraints: "Hard constraints", gateRecord: "Gate record", poc: "Proof of concept", allowlisted: "Allowlisted checks", pocVerified: "PoC verified", noRecipe: "No trusted recipe — research only", syntheticFixture: "synthetic fixture", researchOnly: "research-only", reviewedDocker: "reviewed local Docker", evidence: "Evidence", claimLedger: "Claim ledger", limits: "Limits", doesNotProve: "What this does not prove",
    loadingEvidence: "Loading evidence…", evidenceRecord: "Evidence record", authority: "Authority", evidenceId: "Evidence ID", sourceType: "Source type", sourceTitle: "Source title", sourceHash: "Source hash", snapshot: "Snapshot time", openSource: "Open source", frozenSource: "Frozen synthetic source: no external URL is exposed.", liveEvidence: "Live evidence", cachedEvidence: "Cached evidence", unavailableEvidence: "Unavailable evidence", live: "Live", cached: "Cached", synthetic: "Synthetic", unavailable: "Unavailable", loadingCandidate: "Loading candidate…", candidate: "Candidate", backMatrix: "← Candidate matrix", verdict: "Verdict", compatibility: "Compatibility", requestedVersion: "Requested version", resolvedVersion: "Resolved version", notPinned: "not pinned", notVerified: "not verified", record: "Evidence & PoC record", linked: "linked items", notFoundTitle: "Unable to open file", notFound: "This page is not part of the research desk.", returnDesk: "Return to the research desk",
  },
  "zh-CN": {
    skip: "跳到主要内容", fixture: "合成夹具模式 · 模拟生命周期 · 不调用模型、网络或 Docker", syntheticBoundary: "冻结的合成演示——经过真实 Harness 与本地 MCP 路由，但不主张存在实时 provider 证据或真实 Docker 结果。", home: "MOMO TechScout 首页", desk: "证据与验证工作台", footerWave: "MOMO TechScout / 本地 Wave 2 集成", footerRule: "先有证据，再做推荐。", language: "语言", english: "English", chinese: "中文",
    heroEye: "Wave 2 · 基于 Harness 的组件调研", heroTitleA: "让每个选择", heroTitleB: "都有凭据。", heroDek: "按照硬约束、经本地 MCP 冻结的证据和确定性白名单检查，对比 Python AI 组件。", boundary: "快速演示边界", vectorStores: "本地 RAG 向量存储", boundaryBody: "快速演示完全离线且使用合成数据。只有具备相应 authority 时，Verified 模式才会使用实时 provider 与经审查的 Docker。",
    newTask: "新任务", frame: "定义决策", question: "决策问题", questionPlaceholder: "哪个本地向量存储适合这个服务？", project: "项目背景", python: "Python", os: "操作系统", deployment: "部署方式", constraints: "硬约束", constraintsHint: "每行一项，最多五项", candidates: "候选清单", candidatesHint: "可选，逗号分隔，最多三项", mode: "模式", fast: "快速演示", verified: "Verified（实时数据 + 经审查 Docker）", submitting: "提交中…", start: "启动 TechScout 任务", recent: "最近运行", ledger: "决策台账", fixtureTitle: "合成离线夹具", fixtureBody: "不包含实时证据、模型、Docker 或评估结论。",
    loadingRun: "正在加载运行投影…", runMissing: "未找到运行。", connection: "连接中断——保留最近状态并按退避策略重连。", fixtureElapsed: "夹具耗时", elapsed: "耗时", failed: "运行已安全失败——未发布报告。", failedHelp: "请检查下方稳定失败码；若条件可重试，请创建新任务。", retry: "可通过新建运行重试。", limited: "已完成，但存在限制。", limitedHelp: "报告可用，但以下边界仍然重要。", progress: "TechScout 进度", plan: "规划", planNote: "冻结问题", research: "调研", researchNote: "收集官方证据", verify: "验证", verifyNote: "执行可信配方", decide: "决策", decideNote: "应用确定性 Gate", completed: "已完成", current: "当前", pending: "待处理", currentSkill: "当前技能", currentTool: "当前工具", approval: "审批", recovery: "恢复", matrix: "候选矩阵", awaiting: "等待候选投影", components: "个组件", openReport: "打开决策报告 →", trace: "Trace 事件流", collapse: "收起", expand: "展开",
    loadingReport: "正在加载决策报告…", decisionReport: "决策报告", recommend: "推荐", noWinner: "没有安全胜者", timeline: "← 运行时间线", hardConstraints: "硬约束", gateRecord: "Gate 记录", poc: "概念验证", allowlisted: "白名单检查", pocVerified: "PoC 已验证", noRecipe: "无可信配方——仅调研", syntheticFixture: "合成夹具", researchOnly: "仅调研", reviewedDocker: "经审查的本地 Docker", evidence: "证据", claimLedger: "主张台账", limits: "限制", doesNotProve: "本次结果不能证明什么",
    loadingEvidence: "正在加载证据…", evidenceRecord: "证据记录", authority: "Authority", evidenceId: "证据 ID", sourceType: "来源类型", sourceTitle: "来源标题", sourceHash: "来源哈希", snapshot: "快照时间", openSource: "打开来源", frozenSource: "冻结的合成来源：不提供外部 URL。", liveEvidence: "实时证据", cachedEvidence: "缓存证据", unavailableEvidence: "证据不可用", live: "实时", cached: "缓存", synthetic: "合成", unavailable: "不可用", loadingCandidate: "正在加载候选项…", candidate: "候选项", backMatrix: "← 候选矩阵", verdict: "结论", compatibility: "兼容性", requestedVersion: "请求版本", resolvedVersion: "解析版本", notPinned: "未固定", notVerified: "未验证", record: "证据与 PoC 记录", linked: "条关联记录", notFoundTitle: "无法打开文件", notFound: "此页面不属于调研工作台。", returnDesk: "返回调研工作台",
  },
} as const;

type MessageKey = keyof typeof messages.en;
type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: MessageKey) => string };
const I18nContext = createContext<I18nValue>({ locale: "en", setLocale: () => undefined, t: (key) => messages.en[key] });
function initialLocale(): Locale { try { return localStorage.getItem(STORAGE_KEY) === "zh-CN" ? "zh-CN" : "en"; } catch { return "en"; } }
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, updateLocale] = useState<Locale>(initialLocale);
  const value = useMemo<I18nValue>(() => ({ locale, setLocale(next) { updateLocale(next); document.documentElement.lang = next; try { localStorage.setItem(STORAGE_KEY, next); } catch { /* storage may be disabled */ } }, t: (key) => messages[locale][key] }), [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n() { return useContext(I18nContext); }
